modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
issueTrackerURL = "https://github.com/CielSachen/${mod_name}/issues"

[[mods]]
modId = "${mod_id}"
version = "${minecraft_version}-${mod_version}"
displayName = "${mod_name}"
logoFile = "${mod_id}_banner.png"
credits = "${mod_credits}"
authors = "${mod_authors}"
description = "${mod_description}"

[[dependencies.${mod_id}]]
  modId = "forge"
  mandatory = true
  versionRange = "${forge_version_range}"
  ordering = "NONE"
  side = "BOTH"

[[dependencies.${mod_id}]]
  modId = "minecraft"
  mandatory = true
  versionRange = "${minecraft_version_range}"
  ordering = "NONE"
  side = "BOTH"

[[dependencies.${mod_id}]]
  modId = "curios"
  mandatory = true
  versionRange = "${curios_version_range}"
  ordering = "NONE"
  side = "BOTH"

[modproperties.${mod_id}]
  catalogueItemIcon = "${mod_id}:ruby"
